import { BadRequestException } from "@nestjs/common";

export type EvidencePurpose = "handover" | "refund-proof";

const IMAGE_EXTENSIONS = "(?:jpg|png|webp)";

function configuredOrigin() {
  const value = process.env.SUPABASE_URL?.trim();
  if (!value) throw new BadRequestException("Kho lưu trữ bằng chứng chưa được cấu hình.");
  try {
    return new URL(value.endsWith("/") ? value.slice(0, -1) : value);
  } catch {
    throw new BadRequestException("Kho lưu trữ bằng chứng chưa được cấu hình hợp lệ.");
  }
}

/**
 * Evidence URLs are accepted only when they were generated by the purpose
 * scoped upload boundary for the authenticated actor. This protects the write
 * APIs even when a caller bypasses the frontend upload route.
 */
export function assertOwnedEvidenceUrl(
  value: string,
  options: { purpose: EvidencePurpose; ownerId: string },
): string {
  const trimmed = value.trim();
  let url: URL;
  try {
    url = new URL(trimmed);
  } catch {
    throw new BadRequestException("URL bằng chứng không hợp lệ.");
  }

  const origin = configuredOrigin();
  if (
    url.origin !== origin.origin ||
    url.protocol !== origin.protocol ||
    url.username ||
    url.password ||
    url.search ||
    url.hash
  ) {
    throw new BadRequestException("URL bằng chứng không thuộc kho lưu trữ hợp lệ.");
  }

  const bucket = process.env.SUPABASE_ASSETS_BUCKET?.trim() || "products";
  const prefix = `/storage/v1/object/public/${bucket}/`;
  if (!url.pathname.startsWith(prefix)) {
    throw new BadRequestException("URL bằng chứng không thuộc bucket hợp lệ.");
  }

  let objectPath: string;
  try {
    objectPath = decodeURIComponent(url.pathname.slice(prefix.length));
  } catch {
    throw new BadRequestException("URL bằng chứng không hợp lệ.");
  }

  const escapedOwner = options.ownerId.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const pattern = new RegExp(`^${options.purpose}/${escapedOwner}/[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\\.${IMAGE_EXTENSIONS}$`, "i");
  if (!pattern.test(objectPath)) {
    throw new BadRequestException("URL bằng chứng không thuộc phiên tải lên của bạn.");
  }

  return trimmed;
}

export function assertOwnedEvidenceUrls(values: readonly string[], options: { purpose: EvidencePurpose; ownerId: string }) {
  return values.map((value) => assertOwnedEvidenceUrl(value, options));
}
